### ISSUE TITLE
Error 17

### ISSUE THREAD

**Issue by glaukon** [DavidBPCode/GestionClientes#1]
Muy buenas me gustaria probar la aplicacion y me da este error me puedes ayudar. GRACIAS
Error en la conexión: 17
Fatal error: Call to a member function prepare() on null in C:\xampp\htdocs\GestionClientes\includes\empresa.php on line 29

**Comment by davibern** [comment]
Hola @glaukon perdona por no haber respondido antes pero he estado muy liado y no he podido seguir con el proyecto.

¿Has comprobado que estás conectando bien con tu usuario y contraseña a MySQL? 
¿Has definido correctamente en la base de datos los nombre de las tablas y campos?

**Comment by davibern** [comment]
No es un error de la aplicación. Compruebo que está funcionando correctamente.

**Comment by glaukon** [comment]
Buenas! Le volveré a echar un vistazo. Muchas gracias!!

El 1 abr. 2017 13:48, "David Bernabé" <notifications@github.com> escribió:

No es un error de la aplicación. Compruebo que está funcionando
correctamente.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/DavidBPCode/GestionClientes/issues/1#issuecomment-290915176>,
or mute the thread

**Comment by davibern** [comment]
Tengo pendiente de crear un fichero *.txt con el nombre de la tabla y los campos a utilizar. O bien un fichero *.sql con las instrucciones para crear dicha tabla, a modo de instalación. Me lo apunto como mejora.

Gracias!
